### ISSUE TITLE
Create /now page

### ISSUE THREAD

**Issue by Ryuno-Ki** [inezabonte/inezabonte#144]
See https://nownownow.com/about

**Comment by inezabonte** [comment]
## How will I implement this?
- I will create a markdown file for the `now` page which will have all the content that I need there
- Since it's mdx format I can add components if I need to.
- Parse the mdx content and show it on the `/now` endpoint

## where will I display the link?
- I think the best place to put it would be in the footer since It's not a high priority. I'll reserve the 
navigation bar for the primary pages. What do you think @Ryuno-Ki ?

## what will go on the page?
- Current status
- What I'm currently working on
- Last Updated (date)

**Comment by Ryuno-Ki** [comment]
Looking at https://nownownow.com/about it sounds like to place where you normally would drop an `/about` link.
Footer sounds good.

It's your domain. Do whatever your want :-)
